### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by delokman** [rakutentech/android-miniapp#129]
hello
1) what kind of miniapp package(wechat/tencent/buido) can render by rakutentech sdk?

2) how i can develop sdk  to support specific miniapp package?

thanks a lot

**Comment by corycaywood** [comment]
Hi @delokman 

Thanks for your interest in our project. I'll try to answer your questions:

1. This SDK does not support WeChat, Tencent, or Baidu Mini Apps. Currently, this SDK supports Mini Apps built using standard HTML and JavaScript. One of our goals is to stay as close as possible to web browser standards in order to enable easy porting from the web. Also, the web asset package is delivered to this SDK via a standard ZIP file.

2. Unfortunately, I don't have a good answer on how you can support a specific miniapp package. Some of the companies that you mentioned are working on a W3C standard for Mini Apps and have written a white paper, so that might be a good place to start: https://w3c.github.io/miniapp/white-paper/

Hope that helps!

**Comment by abeshjha** [comment]
@delokman when you say standard mini apps built using html and javascript, where do I get app ID and subscription key for them to run in the sdk?
